services:
  - type: web
    name: keystone
    env: node
    plan: starter
    buildCommand: yarn install --production=false && yarn migrate && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 14.17.3
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: keystone
          property: connectionString
      - key: SESSION_SECERT
        generateValue: true

databases:
  - name: keystone
    plan: starter
